apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-acme-whitelist-updater
subjects:
- kind: ServiceAccount
  name: openshift-acme-whitelist-updater
  namespace: default
roleRef:
  kind: ClusterRole
  name: openshift-acme-whitelist-updater
  apiGroup: rbac.authorization.k8s.io
