apiVersion: v1
kind: DeploymentConfig
metadata:
  name: openshift-acme-whitelist-updater
  labels:
    app: openshift-acme-whitelist-updater
spec:
  replicas: 1
  selector:
    app: openshift-acme-whitelist-updater
    deploymentconfig: openshift-acme-whitelist-updater
  strategy:
    resources: {}
    type: Rolling
  template:
    metadata:
      labels:
        app: openshift-acme-whitelist-updater
        deploymentconfig: openshift-acme-whitelist-updater
    spec:
      serviceAccount: openshift-acme-whitelist-updater
      containers:
      - name: openshift-acme-whitelist-updater
        image: djerfy/openshift-acme-whitelist-updater:latest
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
